# Generated by Django 5.2 on 2025-04-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('due_date', models.DateField()),
                ('prio', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')])),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('await_feedback', 'Await feedback')], default='to_do')),
                ('assigned_contacts', models.ManyToManyField(blank=True, related_name='tasks', to='contacts_app.contact')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.category')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.CharField(max_length=1024)),
                ('is_completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks_app.task')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
                'ordering': ['task'],
            },
        ),
    ]
