# Generated by Django 5.2 on 2025-04-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('await_feedback', 'Await feedback'), ('done', 'Done')], default='to_do'),
        ),
    ]
