# Generated by Django 5.2 on 2025-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='initial',
            field=models.CharField(editable=False, max_length=2),
        ),
    ]
